### ISSUE TITLE
Top module is useless on H1

### ISSUE THREAD

**Issue by xVenora** [awgil/ffxiv_bossmod#257] opened 2024-02-09 00:46 UTC
Shows the exact opposite of what to do
H2 shows what H1 is supposed to do.. (most of the time)

**Comment by awgil** [comment] 2024-02-09 13:10
The priorities for towers/panto are fully configurable:
![image](https://github.com/awgil/ffxiv_bossmod/assets/20607474/5bf3676c-9399-4f95-801b-9193c1db67b0)

The defaults are LPDU:
* for towers, uses global M>T>R>H prios (so H1 would always take the CCW tower, unless having same order as H2)
* for panto, uses light parties with T>M>R flex prio (so H1 should always take the 'north' group) - note that this mechanic is boss-relative, so if your tank faces boss somewhere else, you will see wrong suggestions).

Now, the way you describe problem with towers suggests you use some different strats? What do you mean by your partner being M1 - do you use some sort of light party assignments there too?

For panto, it should not tell you to go south as H1, if you use default configuration and correct assignments, _unless_ your mt faces boss weirdly. If you're sure everything is correctly configured - it's a bug, please send me (a) replay, (b) your config (BossMod.json) file, I'll investigate.

**Comment by awgil** [comment] 2024-02-09 19:04
> the "lower" number flexes means that for example
> if g1 prio 4 and g1 prio 3 conflict
> prio 3 would flex

Yeah - so default LPDU MT is G1 prio1, meaning that he flexes if he has the same order as anyone else from G1, he'll flex. Now that you've said it, I realize it could be interpreted in opposite way (like 'prio1' can be thought of 'top priority for flexing'), feel free to suggest better wording :)

**Comment by awgil** [comment] 2024-02-10 10:44
Discussed in dm, it seems to be working as intended - closing for now, please reopen (and send me a replay + config) if needed.

**Closed by awgil** 2024-02-10 10:44 UTC
