### ISSUE TITLE
Plugin aggressively spams Dalamud log at wrong log level

### ISSUE THREAD

**Issue by reiichi001** [awgil/ffxiv_bossmod#64] opened 2022-10-23 05:17 UTC
Hi there!

I've recently become aware of this plugin due to how it is making a log entry for every single frame/framework entry, which leads to grossly oversized log files and in turn, makes it impossible to troubleshoot other plugins. As a fellow plugin developer, this is concerning, as I often have to provide support to other users and cannot do so when their logs are otherwise being drowned out by other messages that aren't even contributing to troubleshooting for this plugin.

The code in question is:
https://github.com/awgil/ffxiv_bossmod/blob/master/BossMod/Framework/Plugin.cs#L34

The log level should be switched to either Debug or Verbose instead of the Information level, as exceptionally large logs are not only difficult to read but can also lead to crashing Dalamud when launching the game. The information log level is used for relevant non-error logging that a user may need to send to a plugin developer, or to the Dalamud support discord. Debug should be used for WIP code codes, and Verbose is for logging everything else that might be useful for development needs, but not useful for user troubleshooting or errors.

-----

Additionally, I would place extreme caution on trying to automate combat. While this plugin claims it's borrowing ideas from XIVCombo and MouseoverAction, those plugins do not remove player choice. Turning something into a single button rotation and otherwise automating decisions for the player is just botting masquerading under another name, which is generally frowned upon in this community. While we cannot enforce our guidelines on external plugins, I do hope you will take this into consideration given Square Enix's more recent stances on third party tools and the negative player perceptions around once used for botting and cheating.

**Comment by awgil** [comment] 2022-10-23 07:33
Re logs - good point, I'll see what I can do - the problem is that it's not possible (or I don't know how?) to set different log levels for dev plugin compared to normal plugins. Changing log level globally makes it hard for me to work on the plugin (since now I get messages from other plugins that I don't care about). Maybe I'll just use different level for debug/release builds.

Ultimately, this is a plugin that I develop primarily for myself, and I have no intention to promote it for wide use - anyone that finds it and uses it via third-party repo does it at his own risk - and there are enough warnings about that both on dalamud side (the whole 'unsupported third party repo' stuff) and on plugin side (description even mentions that it's an early alpha, and it's probably gonna stay in that state forever).

Re. automation - this plugin definitely automates rotation to a great extent (the whole name 'autorotation' is pretty straightforward). This is opt-in, disabled by default, turned on by an option marked as 'experimental'. You definitely could say it's a bot - it is to a certain extent (it doesn't automate movement, that's why I don't call it that, but I agree that you could have different definitions). You say XIVCombo doesn't remove player choice while my plugin does - I would argue with that, in my mind pressing wrong combo move is not different from not pressing some ogcd at correct moment. There is some player choice in ability use (for example, when to press some defensive cooldown) - you can automate that to a certain extent too (using cooldown planner), but that just moves the moment of the choice from fight execution to fight preparation, and trades some flexibility for consistency. That is the way I prefer playing games, and that is the option that this plugin provides. I definitely do not consider it to be cheating, since the mechanics of the game are not circumvented - it just removes the requirement to memorize button press order and execute them manually, it's basic automation. I would say that actual boss modules are closer to cheating - since they change the information presentation from hints like ability names, animations, etc. to straightforward aoe zones, simplifying mechanic execution - but that still doesn't cross the line for me, which is 'doing something that a player who spent sufficient time practicing still can't do manually'.

**Comment by reiichi001** [comment] 2022-10-23 07:54
Since this is the main reason I opened the issue, I'll elaborate a bit more here.
>Re logs - good point, I'll see what I can do - the problem is that it's not possible (or I don't know how?) to set different log levels for dev plugin compared to normal plugins. Changing log level globally makes it hard for me to work on the plugin (since now I get messages from other plugins that I don't care about). Maybe I'll just use different level for debug/release builds.

**PluginLog.Log()** will use the default log level (Information), but in general, I'd avoid this function since it's a wrapper and a default that could change in the future. (Like how Dalamud Staging defaults to Debug)

The in-game Dalamud log also includes a log filter, which can be adjusted for a specific plugin (including log levels), which can be accessed with `/xllog`. 

Instead, I'd use the following:
**PluginLog.Information()** -> This is the only thing people should see in a release build, barring PluginLog.Error() output. As its name implies, it's for informational logging. Like if you need to note that you're pulling something from an API, or doing an initial load of data. If it's something that only you as the developer should care about, this is not the correct log level.

**PluginLog.Debug()** -> This is what you should use more likely. While it can be switched to even in a release build if a user adjusts their log level from `/xllog` in game, that's then on the user.  Anything you need to log for development/WIP code should typically go here, unless it's something a user should expect to see logged in the release version.

**PluginLog.Verbose()** -> This is what should be used if you're going to be logging something extremely frequently, as in more than once every few seconds, or multiple times per user interaction. (Like your current function that logs every single framework update and every single packet received. A user's log shouldn't really contain that, even if it's something that may be more beneficial for you while doing development). As its name implies, it's where extra verbose logging should go, as the extection is that it's going to drown most things out.

**Comment by awgil** [comment] 2022-10-23 08:03
Yes, I understand the difference between log levels - the problem is that I (as a developer) generally care about the messages that I currently log, so I'd like to see them in my local log file by default (without tweaking loglevel in /xldev menu every time I start up a game), and without seeing debug/verbose stuff from other people's plugins. So I guess it would be nice to configure dalamud to have different default log priorities for dev and non-dev plugins, but that's not possible as far as I understand?

**Comment by awgil** [comment] 2022-10-23 08:06
BTW logging for 'network packets received' is disabled by default, I wonder if I should just disable that altogether from release builds if people select that option without thinking...

**Comment by awgil** [comment] 2022-10-23 08:19
As a hotfix, I've changed default log level to 'debug' in Release builds, I hope that will help. Will think more on how to improve that.

**Closed** 2022-10-23 08:23 UTC
