### ISSUE TITLE
waymarks not showing

### ISSUE THREAD

**Issue by excalibert** [awgil/ffxiv_bossmod#11] opened 2022-04-18 19:28 UTC
waymarks aren't showing on the radar in p3s; haven't checked if elsewhere yet

**Comment by awgil** [comment] 2022-04-19 11:08
Are you sure you've enabled corresponding config option (boss module -> show waymarks)?

Did hint for darkened fire (numbers) mechanic show correct safe spots? If yes, then addon itself knew waymark locations, otherwise (if it showed incorrect position) it didn't have corresponding data.

Currently waymarks are detected using network messages rather than memory scan, so if you e.g. reload plugin while in instance, it won't know anything about waymarks until someone resets them.

**Comment by awgil** [comment] 2022-06-18 20:05
Closing: can't reproduce, no more information provided.

**Closed by awgil** 2022-06-18 20:05 UTC
