### ISSUE TITLE
Use item

### ISSUE THREAD

**Issue by vrBlanky** [awgil/ffxiv_bossmod#9] opened 2022-04-08 13:17 UTC
There's an issue with MSQ quests where trying to use a quest item on a target displays "invalid target" making it unable to proceed

**Comment by awgil** [comment] 2022-04-17 07:28
What is the simplest way to reproduce it? Which quest it was?

**Comment by vrBlanky** [comment] 2022-04-17 10:40
> What is the simplest way to reproduce it? Which quest it was?

Blank#8888 I'd be able to send a gif to demonstrate, and explain, basically with the mod installed, whatever quest it is, you're unable to use the quest item.

**Comment by AserAlmighty** [comment] 2022-04-22 14:21
Any quest item that needs to be used on a target can't be used and you get the 'Invalid Target' error. Happened in the Sylph beast tribe quests, WAR job quest and during the MSQ for me.

**Comment by awgil** [comment] 2022-04-22 14:35
What are the names of the quests? Sylph in particular should be easy to reproduce. And I need to reproduce it to investigate the reason.

**Comment by AserAlmighty** [comment] 2022-04-22 14:58
The Sylph one is called 'Feed Me' and the WAR one is called 'The Bear Necessity' which you can replay with the NG+ feature I guess, so that's easy.

**Comment by awgil** [comment] 2022-04-22 16:33
Interesting, do you by chance have a similar problem with MOAction addon? Apparently it's the hack I've lifted from it that is causing this...

**Comment by awgil** [comment] 2022-04-22 17:01
Should be fixed, please try new version...

**Closed by awgil** 2022-04-22 17:01 UTC
